---
 - name: Install EPEL lib in YUM
   hosts: planetexpress
   become: yes # run entrie playbook with sudo 

   tasks:
    - name: "install epel-release"
      yum:
        name: epel-release
        state: present
      when: ansible_distribution == "CentOS"

    - name: "Update yum repos and install package X"
      yum:
        update_cache: True
        name: 
            - fail2ban
            - moon-buggy
        state: latest
      when: ansible_distribution == "CentOS"


