---
- name: How to prompt for variables
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: "yourpassword" # variable name to define
      prompt: "what is  your pw?" # questions to ask
      #private: yes # don't reveal the pw
      ## run this encryption method 
      #encrypt: "sha512_crypt"
      # type the password twice
      confirm: yes
      # this is the size of the RAND you'd like to have generated
      #salt_size: 7
      # salt: slappysquirrel88 # provide your own RAND
      # default to this password
      #default: "qwerty"

  tasks:
    - name: print out the pw
      debug: 
        msg: "{{ yourpassword }}"

